services:
  - type: web
    name: sign-language-traductor
    env: python
    region: frankfurt   # plus proche de la Tunisie
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: modele_tunisien.pkl
      - key: LABELS_PATH
        value: labels_tunisiens.json
    healthCheckPath: /health
